// This file was auto-generated by Fern from our API Definition.

package api

import (
	core "github.com/fern-api/fern-go/internal/testdata/sdk/error/fixtures/core"
)

type UntypedError struct {
	*core.APIError
}
